### ISSUE TITLE
IAR C-SPY Debug for VS Code - $PROJ_DIR$ path incorrectly be expanded to <ewp path>/.vscode/ in .board file

### ISSUE THREAD

**Issue by Ayumiiw** [IARSystems/iar-vsc-debug#18]
When there is a relative path "$PROJ_DIR$" for <loader> element in .board file,  cannot start debug session with the following error.

`Flash loader file does not exist or is of invalid format:[C:\path\to\project\file\.vscode\FlashLoader\flashloader_ijet\FlashXXXX.flash]`

It seems that the "$PROJ_DIR$" in .board file will be expanded to "<ewp path>/.vscode/" when using VSCode.
If I specify the absolute path for .flash file in .board file, then it succeeded to start debug session.

This was confirmed with IAR C-SPY debug extension 1.20.1 + IAR Embedded Workbench for Arm 9.32.1.

Regards,

**Comment by HampusAdolfsson** [comment]
This was fixed in 1.20.2, but I forgot to close it.
