### ISSUE TITLE
I removed the breakpoint, but the break still works

### ISSUE THREAD

**Issue by olreng** [IARSystems/iar-vsc-debug#22]
other breakpoint is work well in other code
but specific code is break continuesly after remove breakpoint

iar toolchain: embedded workbench 8.4(Arm)

**Comment by jlonnberg** [comment]
@olreng Could you please provide some more information. Which driver are you using and which version of the visual studio code extension? Could you please include the trace information for a session where the problem occurs? Trace can be enabled by adding ""trace": true" to the launch configuration.

**Comment by olreng** [comment]
Sorry, I was trying to recreate the same situation.
suddenly not able to reproduced.
If it reproduced again, I will leave it again
