### ISSUE TITLE
Watch window variable value edit inconsitency

### ISSUE THREAD

**Issue by davidanderle** [IARSystems/iar-vsc-debug#23]
Hello,
I've been having a play around with the watch window in VSCode and I've spotted 2 issues:

1. Although the "Set value" functionality is shown, the last element of an array in the watch window cannot be modified. When you set the element's new value, it simply doesn't update. As a workaround you can update the value in the local/static variables window without an issue.
2. A scalar variable's value cannot be modified in the watch window, only under the local/static variables window.

Here's a quick demonstration:
https://github.com/IARSystems/iar-vsc-debug/assets/17354704/d3d09663-6a80-4632-aeb9-58f59eb05cf8

As a side-note, is there a way to colour numbers with an apostrophe in their digits the same colour as ones without? For example, in the demonstration video above you can see that 999 is green, while 1'000 is grey. This apostrophe number interpretation of C-SPY is extremely useful so I would use this feature over the colour mismatch at any point :)

**Comment by HampusAdolfsson** [comment]
Hi,

I will look into the issues you found. Regarding the colouring of values in the watch (and variables) window, VS Code automatically classifies the values into different types depending *only* on the value, and uses this to determine the color. Numbers with apostrophes are classified as generic 'values', not 'numbers'.

A workaround is to override the colors used by VS Code, by placing this in your settings:
```json
    "workbench.colorCustomizations": {
        "debugTokenExpression.number": "#cccccc99",
    }
```
or
```json
    "workbench.colorCustomizations": {
        "debugTokenExpression.value": "#b5cea8",
    }
```

**Comment by davidanderle** [comment]
Hi,
Thanks for looking into it! The colour customisation settings worked but as expected <struct>s and <array>s are now also coloured green:
![image](https://github.com/IARSystems/iar-vsc-debug/assets/17354704/c2cc28ed-6d10-4778-b2d2-dc1f824ff311)
This still gives a more coherent look to me so I'll set this for my setup.

**Comment by HampusAdolfsson** [comment]
Yes, probably some time in June.
