### ISSUE TITLE
Emulated printf() to Debug Console showing extra strings 

### ISSUE THREAD

**Issue by davidanderle** [IARSystems/iar-vsc-debug#25]
Hello,

I've spotted that the emulated I/O printf output to the Debug Console has some extra metadata displayed and I could not find any obvious settings in VSCode that may turn this off. 
![image](https://github.com/IARSystems/iar-vsc-debug/assets/17354704/778ec8e9-11ba-4550-a884-c4350d393e90)
On the screenshot above I would expect the string:
"CF\n"
"0-0-0-0-0-0-0-D3\n"

Could you please have a look?

**Comment by HampusAdolfsson** [comment]
Hi,

This logging occurs when you have set the option `"trace": true` in your launch.json file.

**Comment by davidanderle** [comment]
Hi @HampusAdolfsson,
Thanks, confirmed that removing the option from my launch.json "solves" this behaviour.
