### ISSUE TITLE
Peripheral view search does not always filter

### ISSUE THREAD

**Issue by davidanderle** [IARSystems/iar-vsc-debug#27]
In debug mode the Peripheral View window has a search functionality that is meant to filter out all the unwanted registers. For example, the correct display for the STM32G473 when searching for I2C4 is this:
![image](https://github.com/IARSystems/iar-vsc-debug/assets/17354704/ffba9d60-9e5a-4501-8c58-3bc69d502c5f)

Yet when the debugger is re-attached, the "invalid" search results do not disappear:
![image](https://github.com/IARSystems/iar-vsc-debug/assets/17354704/a3bf4497-729a-4a92-8307-3bb6a4671a00)

If, however, I search for a keyword that's not found in any of the peripherals, the list completely disappears. After this if I now type in a keyword that's present in at least one of the peripherals, the filtering works correctly. Here's a little demonstration:
https://github.com/IARSystems/iar-vsc-debug/assets/17354704/74b1e345-c502-437a-9204-c4bc923ff9d2

**Comment by HampusAdolfsson** [comment]
Hi!

The Peripheral View is provided by Microsoft's Embedded Tools extension. It is installed automatically when you install the IAR C-SPY Debug extension, but we are not involved in developing it. This sounds like it should be reported to the Embedded Tools repository instead:
https://github.com/microsoft/vscode-embedded-tools

**Comment by davidanderle** [comment]
Thanks, issue submitted!
