### ISSUE TITLE
Support for live watch

### ISSUE THREAD

**Issue by MrWhatZitToYaa** [iarsystems/iar-vsc-debug#28]
Hi,

I am using IAR Workbench 5.10 for RL78 and the C-Spy Debug extension in VSC. I would like to know if there exists a possibility for live watch in the VSC C-Spy Debug extension just like in the workbench,. It seems that I am only able to find "regular" watch. Is this feature planned for the future?

**Comment by micaelbo** [comment]
Hi. Yes, this is planned for a future release. No date set but it is one of the prioritized improvements. Duplicates #3
