### ISSUE TITLE
Add a Live Watch side bar view

### ISSUE THREAD

**Issue by Spaark84** [iarsystems/iar-vsc-debug#3]
Add a Live Watch side bar view with customizable update interval like it exists in the IAR Embedded Workbench IDE.

**Comment by MrDanielGerber** [comment]
Agreed. Probably one of my most used features in EW

**Comment by zrh-github** [comment]
Agreed2. I need it so much。

**Comment by kzoltaan** [comment]
Agreed3! I want it now! 👍

**Comment by micaelbo** [comment]
It is planned, not for next release but hopefully the one after that. No date set yet.

**Comment by MrHouM** [comment]
> Add a Live Watch side bar view with customizable update interval like it exists in the IAR Embedded Workbench IDE.



> Add a Live Watch side bar view with customizable update interval like it exists in the IAR Embedded Workbench IDE.

i need it so much，come on as soon as possible，thanks very much，love you！

**Comment by HampusAdolfsson** [comment]
The latest release `1.40.1` includes several new views, including a Live Watch window! Please give us any feedback you have on this feature, either here or in a new ticket.
