### ISSUE TITLE
how can i change the vsc-debug variable displayed format？ the default format is decimal

### ISSUE THREAD

**Issue by TwoBrushes** [IARSystems/iar-vsc-debug#30]

**Comment by HampusAdolfsson** [comment]
This is not supported currently, but we are aware that it's a highly requested feature.

See #13 (closing this as duplicate)

**Comment by TwoBrushes** [comment]
> This is not supported currently, but we are aware that it's a highly requested feature.
> 
> See #13 (closing this as duplicate)

How can I view the content of a specific memory address in vsc-debug like in iar?

**Comment by HampusAdolfsson** [comment]
VS Code's memory view doesn't have this feature at the moment. It can only inspect memory at the address of specific variables/expressions.

You can get around this by adding an expression to the 'Watch' window that points to the address you want to inspect, and then pressing the 'View Binary Data' button. The following example will let you inspect the memory at address `0x1234`:
![image](https://github.com/IARSystems/iar-vsc-debug/assets/15944368/5c756baf-08f8-4799-a8c0-5e1ff6dcb9c8)
