### ISSUE TITLE
Continue don't work

### ISSUE THREAD

**Issue by lumal21** [IARSystems/iar-vsc-debug#33]
Hi, 

I'm trying to use the vscode extension to debug using j-link and c-spy, but when it runs continue the debug session no longer works.

Changing the cspyRunControlService.ts file in the continue method on line 113 to use this.dbgr.service.go instead of this.dbgr.service.multiGo(-1) when it is single core. The extension starts to behave as expected.

Attached is the debug console log, the launch.json used, and diff of the modification that made it work.

Versions:
VSCode: 1.84.2
IAR C-SPY Debug: 1.30.3
IAR Workbench: 8.50.6

[launch.json](https://github.com/IARSystems/iar-vsc-debug/files/13487285/launch.json)
[debug_console.txt](https://github.com/IARSystems/iar-vsc-debug/files/13487286/debug_console.txt)
[diff.txt](https://github.com/IARSystems/iar-vsc-debug/files/13499728/diff.txt)

**Comment by HampusAdolfsson** [comment]
Hi,

Thanks for the great bug report! I've applied your fix, it will be included in the next release.
