### ISSUE TITLE
Debug session is not aborted after debugger error

### ISSUE THREAD

**Issue by pawelszramowski** [iarsystems/iar-vsc-debug#35]
**Describe the bug:**

I have a flaky J-Link that frequently causes an error like this:
![image](https://github.com/IARSystems/iar-vsc-debug/assets/27921321/566c5ca0-84e4-4295-a333-baaa72278e38)

When I agree to abort the debug session by clicking Yes in the message box, the debug session is not actually aborted. I need to `Stop (Shift+F5)` it manually.

**To Reproduce:**

Have the debugger report an error... Disconnecting the debugger from the computer may have the same effect but I haven't checked.

**Expected behavior:**

The debug session is aborted after clicking Yes.

**Actual behavior:**

The debug session is not aborted after clicking Yes.

**Environment:**

- OS: Windows
- Embedded Workbench: Arm
- Embedded Workbench version: 8.4
- VSC Extension version: v1.30.4

**Additional context:**

Output from IAR C-SPY Debug:
```
[6/14/2024, 2:47:29 PM][Debug] Failed to generate config from build extension: Error: Could not get C-SPY cmdline
[6/14/2024, 2:47:35 PM][Debug] Session Tracker: Started 'Project.Debug'
[6/14/2024, 2:51:17 PM][Debug] Session Tracker: Terminated 'Project.Debug'
```

The first line shows after I `Start debugging (F5)`.
The second line shows after I select the debugger.
The last line shows after I manually `Stop (Shift + F5)` the debug session.

**Comment by HampusAdolfsson** [comment]
Hi!

I've fixed a bug that caused the debug session not to abort when encountering a fatal error. I haven't been able to reproduce your specific error, but disconnecting the board mid-session produces a similar dialog which is now able to properly abort the session. I am fairly confident this will work for the dialog you're describing too. The fix will be included in the next release.
