### ISSUE TITLE
Peripheral view shows no register values

### ISSUE THREAD

**Issue by Spaark84** [IARSystems/iar-vsc-debug#4]
The peripheral view shows no register values in my case.

![image](https://user-images.githubusercontent.com/58564478/174304513-f9e05e37-ae80-4592-92d8-eda6601e6124.png)

My program runs on an STM32WB55 and I'm using an ST-LINK/V3 debug probe with SWD. The peripherals are enabled and the register values are shown in the IAR Embedded Workbench IDE.

However, I'm not sure if this is a problem of the IAR C-SPY Debug extension or rather of the Embedded Tools extension.

**Comment by HampusAdolfsson** [comment]
This is a data formatting issue on our end, which should be easily fixable.
